services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    build:
      context: .
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      ZENTRO_RELOAD: "True"

  taskiq-worker:
    volumes:
      # Adds current directory as volume.
      - .:/app/src/
    command:
      - taskiq
      - worker
      - zentro.tkq:broker
      - --reload
